# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 2, 14, 29, 45, 216147, tzinfo=utc)),
        ),
    ]
